use_frameworks!

platform :ios, '9.0'

target 'MTLayoutUtilityComponent_Example' do
  pod 'MTLayoutUtilityComponent', :path => '../'

  target 'MTLayoutUtilityComponent_Tests' do
    inherit! :search_paths

    
  end
end
